configuration:
  configuration_dir: "commons/config"
  template_dir:
    - "commons/templates"
    - "setupmobans/templates"
    - ".moban.d"
  configuration: pyexcel.yml
targets:
  - setup.py: setup.py
  - "docs/source/conf.py": "docs/source/conf.py"
  - .travis.yml: travis.yml
  - requirements.txt: requirements.txt.jj2
  - min_requirements.txt: pyexcel_min_requirements.txt
  - "tests/requirements.txt": "tests/requirements.txt"
  - LICENSE: NEW_BSD_LICENSE.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - README.rst: README.rst
  - "docs/source/guide.rst": "docs/source/guide.rst"
  - test.sh: test.sh
  - test.bat: test.bat
  - .gitignore: commons-gitignore.jj2
  - "docs/source/index.rst": "docs/source/index.rst.jj2"
  - "pyexcel/__version__.py": version.txt